"""High-level typed client for the Touchy-Pad device.

Wraps a :class:`Transport` with protobuf encoding/decoding so callers see
typed messages instead of raw bytes.
"""

from __future__ import annotations

import logging
import threading
from collections.abc import Callable, Iterable, Iterator

from .. import _proto  # generated by `just build-proto-py`
from ._transport import Transport, UsbTransport
from .errors import TouchyError

logger = logging.getLogger(__name__)
# Per-RPC send/recv trace lines fire on every host poll (event_consume is
# called ~20×/s by the background event thread) and drown out other DEBUG
# output. Put them on a child logger so callers can silence just this
# stream with::
#
#     logging.getLogger("touchy_pad.api.client.rpc").setLevel(logging.INFO)
#
# while still seeing DEBUG from the rest of the package.
rpc_logger = logger.getChild("rpc")

# Stage 64.1: tunneled device log lines are routed onto this logger
# (with the originating ESP_LOG tag attached via ``extra``). Callers
# can configure formatting/filtering on it just like any stdlib
# logger; in particular the trace-level child logger isolates the
# very noisy ``LOG_PRIORITY_TRACE`` stream so it can be silenced
# independently.
device_logger = logging.getLogger("touchy_pad.device")
device_trace_logger = device_logger.getChild("trace")

# Mapping from the wire-level ``LogPriority`` enum to stdlib logging
# levels. ``LOG_PRIORITY_TRACE`` is routed to ``DEBUG`` on the trace
# child logger; everything else goes straight onto ``device_logger``.
_PRIORITY_TO_LEVEL: dict[int, int] = {
    # populated lazily on first use to avoid touching the enum at
    # import time (and to keep this module importable even if the
    # generated proto is stale).
}

HostEventHandler = Callable[["_proto.LvEvent"], None]


def _check(response: _proto.Response) -> _proto.Response:
    if response.code != _proto.RESULT_OK:
        name = _proto.ResultCode.Name(response.code)
        raise TouchyError(response.code, name)
    return response


class TouchyClient:
    """Low-level interface to a connected Touchy-Pad device.

    Construct via :meth:`open` (uses :class:`UsbTransport`) or pass any
    custom :class:`Transport` (e.g. a loopback for tests).
    """

    def __init__(self, transport: Transport) -> None:
        self._t = transport
        self._host_handlers: dict[int, HostEventHandler] = {}
        # Serializes send_command/recv_response pairs so the high-level
        # Touchy's background event-poll thread can't interleave its
        # RPCs with foreground calls on the same transport (which would
        # cross-route the responses).
        self._rpc_lock = threading.Lock()
        # Stage 64.1: ``drain_pending()`` may surface an ``LvEvent``
        # while draining tunneled log records at connect time; we
        # park it here so the next ``event_consume()`` call returns
        # it instead of polling the device again.
        self._pending_event: _proto.LvEvent | None = None

    @classmethod
    def open(cls) -> TouchyClient:
        # Stage 63: honour TOUCHY_SIM_URL before USB enumeration so a
        # bare `TouchyClient.open()` transparently picks up an
        # out-of-process simulator just by exporting the env var.
        from ._transport_net import TcpTransport, sim_url_from_env

        url = sim_url_from_env()
        if url is not None:
            client = cls(TcpTransport(*url))
        else:
            # Stage 83: try native USB first, then UART-bridge auto-discovery
            # (CH340-attached CYD boards). Re-raise the USB-specific
            # not-found error if neither finds a device.
            try:
                client = cls(UsbTransport())
            except Exception:
                try:
                    from ._transport_serial import (
                        SerialTransport,
                        discover_serial_ports,
                    )
                except Exception:  # noqa: BLE001 - pyserial optional
                    raise
                serial_transport = None
                for path in discover_serial_ports():
                    try:
                        serial_transport = SerialTransport(path)
                        break
                    except Exception:  # noqa: BLE001 - try next candidate
                        logger.debug(
                            "TouchyClient.open: serial port %s did not open; " "trying next",
                            path,
                        )
                        continue
                if serial_transport is None:
                    raise
                client = cls(serial_transport)
        # Stage 64.1: device may have buffered ESP_LOG records since
        # boot (or across a previous host disconnect). Drain them
        # eagerly so they surface on `device_logger` before the
        # caller's first foreground RPC — both as user-visible
        # context and to make sure no stale frame bytes remain in
        # the vendor-bulk FIFO.
        try:
            client.drain_pending()
        except Exception:  # noqa: BLE001 — best-effort
            logger.debug("drain_pending() raised at open; ignoring", exc_info=True)
        return client

    def close(self) -> None:
        self._t.close()

    def __enter__(self) -> TouchyClient:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    # -- internal RPC helper -----------------------------------------------

    def _rpc(self, command: _proto.Command) -> _proto.Response:
        which = command.WhichOneof("cmd")
        with self._rpc_lock:
            rpc_logger.debug("rpc -> %s", which)
            self._t.send_command(command.SerializeToString())
            reply = _proto.Response()
            reply.ParseFromString(self._t.recv_response())
            rpc_logger.debug("rpc <- %s code=%d", which, reply.code)
        return reply

    # -- typed wrappers ----------------------------------------------------

    def sys_board_info_get(self) -> _proto.SysBoardInfoResponse:
        reply = _check(self._rpc(_proto.Command(sys_board_info_get=_proto.SysBoardInfoGetCmd())))
        return reply.sys_board_info

    def sys_reboot_bootloader(self) -> None:
        _check(self._rpc(_proto.Command(sys_reboot_bootloader=_proto.SysRebootBootloaderCmd())))

    def screen_wake(self) -> None:
        _check(self._rpc(_proto.Command(screen_wake=_proto.ScreenWakeCmd())))

    def set_preferences(self, prefs: _proto.PreferencesFile) -> None:
        """Apply a partial preferences update on the device.

        Stage 82 — *prefs* should carry only the fields you want changed
        (every value field has explicit presence). The device merges them
        into its master settings, fires each field's side effect (backlight
        timeout, screen switch, log threshold, …) and persists the result.
        Never set ``prefs.file_version`` — that is device-owned.
        """
        _check(self._rpc(_proto.Command(set_preferences=_proto.SetPreferencesCmd(prefs=prefs))))

    def get_preferences(self) -> _proto.PreferencesFile:
        """Read the device's current, merged preferences.

        Stage LB4 — the device replies with the full ``PreferencesFile``,
        including the device-owned ``file_version``. Used by
        ``touchy pref json-get`` to dump the live settings as JSON.
        """
        reply = _check(self._rpc(_proto.Command(get_preferences=_proto.GetPreferencesCmd())))
        return reply.preferences_read.prefs

    def screen_sleep_timeout(self, timeout_ms: int) -> None:
        """Set the backlight auto-sleep timeout (Stage 82: via SetPreferences)."""
        self.set_preferences(_proto.PreferencesFile(screen_timeout_ms=timeout_ms))

    def set_min_log_level(self, level: int) -> None:
        """Set the minimum log priority the device queues for the host.

        *level* is a :class:`LogPriority` value (0=TRACE … 4=ERROR). Lines
        below it are dropped device-side and never tunneled to the host.
        """
        self.set_preferences(_proto.PreferencesFile(min_log_level=level))

    def set_boot_delay(self, seconds: int) -> None:
        """Set the persistent early-boot delay (seconds; 0 disables).

        Stage 82 — gives a host debug-log connection time to attach before
        the device brings up its UI. Applied at the next boot.
        """
        self.set_preferences(_proto.PreferencesFile(boot_delay_s=seconds))

    def set_backlight_level(self, level: int) -> None:
        """Set the persistent display brightness (0 = off … 100 = max).

        Stage 94 — the device maps the level onto its panel-specific PWM
        duty (or quantises to on/off on expander-driven backlights) and
        persists it so the brightness survives a reboot.
        """
        self.set_preferences(_proto.PreferencesFile(backlight_level=level))

    def run_actions(self, actions: Iterable[_proto.Action]) -> None:
        """Run a list of Actions device-side as if a local widget fired them.

        Stage 71 — used to drive device-local behaviour from the host,
        e.g. forcing a page to the front via an ``ActionChangeWidgetRef``
        without a user touch. The device replies with a bare ``Response``.
        """
        _check(self._rpc(_proto.Command(run_actions=_proto.RunActionsCmd(actions=list(actions)))))

    # Maximum payload bytes per FileWriteCmd. The on-wire protobuf
    # frame must fit inside the device's RX buffer (HOST_API_RX_MAX,
    # 5 KiB in firmware/main/host_api.cpp after stage 51); we leave
    # ~1 KiB of headroom for the surrounding Command / oneof overhead.
    _FILE_WRITE_CHUNK = 4096

    def file_delete(self, path: str) -> None:
        """Delete a file or directory subtree from the device filesystem.

        *path* must be drive-prefixed, e.g. ``"F:host/s/home.pb"``
        or ``"F:host"`` to wipe the whole host-uploaded area on flash.
        Passing ``"R:host"`` wipes the PSRAM filesystem instead.
        """
        logger.debug("file_delete: %s", path)
        _check(self._rpc(_proto.Command(file_delete=_proto.FileDeleteCmd(path=path))))

    def file_open_write(self, path: str) -> int:
        """Begin streaming a new file. Returns an opaque write handle."""
        reply = _check(
            self._rpc(_proto.Command(file_open_write=_proto.FileOpenWriteCmd(path=path)))
        )
        return reply.file_open_write.handle

    def file_write(self, handle: int, data: bytes) -> None:
        """Append a chunk of bytes to an in-progress file write."""
        _check(
            self._rpc(
                _proto.Command(file_write=_proto.FileWriteCmd(handle=handle, data=bytes(data)))
            )
        )

    def file_close(self, handle: int, commit: bool) -> None:
        """Finish (commit=True) or abort (commit=False) a streaming write."""
        _check(
            self._rpc(_proto.Command(file_close=_proto.FileCloseCmd(handle=handle, commit=commit)))
        )

    def file_save(
        self,
        path: str,
        data: bytes | str,
        *,
        max_width: int | None = None,
        max_height: int | None = None,
    ) -> None:
        """Write a file to the device filesystem in one logical call.

        *path* is the drive-prefixed filesystem path
        (e.g. ``"F:host/s/home.pb"`` for persistent flash or
        ``"R:host/images/sdk_key_0.bin"`` for transient PSRAM storage).
        *data* may be ``bytes`` (for binary files such as images) or
        ``str`` (for text payloads, encoded as UTF-8).

        Image bytes (BMP / PNG / JPEG / GIF / WebP — anything Pillow can
        decode) are transparently converted to LVGL's native ``.bin``
        format before upload, so the firmware only needs its always-on
        built-in image decoder. Already-converted ``.bin`` blobs and
        non-image payloads are passed through unchanged.

        *max_width* and *max_height* — if given, the image is scaled down
        (preserving aspect ratio) so that neither dimension exceeds the
        respective limit before conversion.  Values are in pixels.  Non-image
        payloads silently ignore these parameters.

        On the wire this issues a ``FileOpenWrite`` command, one or more
        ``FileWrite`` chunks (≤ 4 KiB each so the on-wire frame fits in
        the device RX buffer) and a ``FileClose(commit=True)``. If any
        chunk fails we send ``FileClose(commit=False)`` so the device
        can drop the partial file.
        """
        if isinstance(data, str):
            data = data.encode("utf-8")
        else:
            data = bytes(data)
        from .lvgl_image import (
            is_gif,
            looks_like_supported_image,
            rescale_gif,
            rewrite_to_bin_path,
            to_lvgl_bin,
        )

        if is_gif(data):
            # GIFs are uploaded verbatim — the firmware renders them with
            # its native lv_gif decoder (Stage 80) and the `.gif` path is
            # the discriminator, so we never convert to LVGL `.bin`. Only
            # rescale the frames when a size limit is requested.
            if max_width is not None or max_height is not None:
                data = rescale_gif(data, max_width=max_width, max_height=max_height)
            logger.debug("file_save: %s (%d bytes gif, unconverted)", path, len(data))
        elif looks_like_supported_image(data) and self._t.needs_image_conversion:
            original_len = len(data)
            data = to_lvgl_bin(data, dest_path=path, max_width=max_width, max_height=max_height)
            # LVGL's bin decoder selects itself by extension, so the
            # on-device file has to be named *.bin even though the
            # caller likely passed e.g. "F:host/images/avatar.png".
            path = rewrite_to_bin_path(path)
            logger.debug(
                "file_save: %s (%d bytes source → %d bytes LVGL bin)",
                path,
                original_len,
                len(data),
            )
        else:
            logger.debug("file_save: %s (%d bytes)", path, len(data))
        handle = self.file_open_write(path)
        committed = False
        try:
            for offset in range(0, len(data), self._FILE_WRITE_CHUNK):
                self.file_write(handle, data[offset : offset + self._FILE_WRITE_CHUNK])
            self.file_close(handle, commit=True)
            committed = True
        finally:
            if not committed:
                # Best-effort abort; swallow any follow-up error so the
                # original exception is what propagates.
                try:
                    self.file_close(handle, commit=False)
                except Exception:  # noqa: BLE001
                    pass

    def screen_load(self, path: str) -> None:
        """Activate a previously-uploaded screen.

        *path* is the full drive-prefixed path the screen was uploaded
        to (e.g. ``"F:host/s/home.pb"``). Passing an empty string
        loads the device's default screen.

        Stage 82 — implemented over ``SetPreferencesCmd`` (sets
        ``current_screen``), which both switches the displayed screen and
        persists it across reboots.
        """
        logger.debug("screen_load: %s", path or "(default)")
        self.set_preferences(_proto.PreferencesFile(current_screen=path))

    def event_consume(self) -> _proto.LvEvent | None:
        """Pop one pending event from the device queue, or return ``None``.

        Returns ``None`` only when the device's event *and* log queues
        are both empty. Stage 64.1: tunneled ``LogRecord`` payloads
        are consumed transparently (dispatched to :data:`device_logger`)
        and we keep polling in the same call until either an
        ``LvEvent`` surfaces or the device reports ``RESULT_NOT_FOUND``
        — that way the caller's poll-and-sleep loop doesn't insert
        ``poll_interval_ms`` of latency between consecutive log
        records.
        """
        if self._pending_event is not None:
            evt, self._pending_event = self._pending_event, None
            return evt
        while True:
            item = self.poll()
            if item is None:
                return None
            if isinstance(item, _proto.LvEvent):
                return item
            # LogRecord — dispatch and keep draining; there may be
            # more logs queued, or an event right behind them.
            self._dispatch_log_record(item)

    def drain_pending(self, max_iterations: int = 256) -> None:
        """Drain queued events and log records from the device.

        Log records are dispatched to :data:`device_logger`. If an
        ``LvEvent`` surfaces during the drain it is parked for the
        next :meth:`event_consume` call so no event is lost. Caps at
        ``max_iterations`` polls as a runaway guard.
        """
        for _ in range(max_iterations):
            item = self.poll()
            if item is None:
                return
            if isinstance(item, _proto.LvEvent):
                # Save for the next event_consume; stop draining so
                # subsequent logs queued behind this event are picked
                # up by the normal polling loop (which preserves the
                # device-side events-first ordering).
                self._pending_event = item
                return
            self._dispatch_log_record(item)

    def poll(self) -> _proto.LvEvent | _proto.LogRecord | None:
        """Low-level drain: pop one event or log record from the device.

        Returns whichever of an ``LvEvent`` or ``LogRecord`` the device
        had pending (events take priority on the firmware side), or
        ``None`` when both queues are empty.
        """
        reply = self._rpc(_proto.Command(event_consume=_proto.EventConsumeCmd()))
        if reply.code == _proto.RESULT_NOT_FOUND:
            return None
        _check(reply)
        if reply.HasField("event_consume") and reply.event_consume.HasField("event"):
            return reply.event_consume.event
        if reply.HasField("log_record"):
            return reply.log_record
        return None

    # -- log dispatch -------------------------------------------------------

    @staticmethod
    def _priority_to_level(priority: int) -> tuple[logging.Logger, int]:
        if not _PRIORITY_TO_LEVEL:
            _PRIORITY_TO_LEVEL.update(
                {
                    _proto.LOG_PRIORITY_TRACE: logging.DEBUG,
                    _proto.LOG_PRIORITY_DEBUG: logging.DEBUG,
                    _proto.LOG_PRIORITY_INFO: logging.INFO,
                    _proto.LOG_PRIORITY_WARN: logging.WARNING,
                    _proto.LOG_PRIORITY_ERROR: logging.ERROR,
                }
            )
        level = _PRIORITY_TO_LEVEL.get(priority, logging.DEBUG)
        # TRACE goes onto the dedicated trace child so it can be
        # silenced without losing DEBUG output from real device DEBUG
        # logs.
        if priority == _proto.LOG_PRIORITY_TRACE:
            return device_trace_logger, level
        return device_logger, level

    def _dispatch_log_record(self, rec: _proto.LogRecord) -> None:
        target, level = self._priority_to_level(rec.priority)
        # ``extra`` makes the originating ESP_LOG TAG visible to custom
        # log formatters without polluting the message body.
        target.log(
            level,
            "%s",
            rec.message,
            extra={"device_tag": rec.tag, "device_timestamp_ms": rec.timestamp_ms},
        )
        if rec.num_dropped:
            device_logger.warning(
                "device dropped %d log record(s) before this one",
                rec.num_dropped,
            )

    # -- host event dispatch ------------------------------------------------

    def on_host_event(self, code: int, handler: HostEventHandler) -> None:
        """Register a callback for incoming `ActionHost` events with `host_code == code`.

        The callback receives the full :class:`_proto.LvEvent` so it can
        inspect ``user_data`` (the firing widget's id) and the ``state``
        oneof (``value`` for sliders, ``checked`` for switches/checkboxes).
        """
        self._host_handlers[code] = handler

    def _dispatch_host_event(self, evt: _proto.LvEvent) -> None:
        h = self._host_handlers.get(evt.host_code)
        if h is not None:
            h(evt)

    def stream_events(self, poll_interval_ms: int = 50) -> Iterator[_proto.LvEvent]:
        """Yield LvEvents from the device until the transport closes.

        The ESP32-S3 USB-OTG controller doesn't have a free IN endpoint
        for a dedicated event mailbox, so the host polls
        :meth:`event_consume` on the bulk command/response pair instead.
        Each call drains the device queue to empty; if the queue was empty
        we sleep ``poll_interval_ms`` before trying again. Each yielded
        event is also routed through :meth:`on_host_event` handlers (if
        any are registered for its ``host_code``).
        """
        import time

        while True:
            evt = self.event_consume()
            if evt is None:
                time.sleep(poll_interval_ms / 1000.0)
                continue
            self._dispatch_host_event(evt)
            yield evt
