"""High-level typed client for the Touchy-Pad device.

Wraps a :class:`Transport` with protobuf encoding/decoding so callers see
typed messages instead of raw bytes.
"""

from __future__ import annotations

import logging
import threading
from collections.abc import Callable, Iterator

from . import _proto  # generated by `just build-proto-py`
from .transport import Transport, UsbTransport

logger = logging.getLogger(__name__)
# Per-RPC send/recv trace lines fire on every host poll (event_consume is
# called ~20×/s by the background event thread) and drown out other DEBUG
# output. Put them on a child logger so callers can silence just this
# stream with::
#
#     logging.getLogger("touchy_pad.client.rpc").setLevel(logging.INFO)
#
# while still seeing DEBUG from the rest of the package.
rpc_logger = logger.getChild("rpc")

HostEventHandler = Callable[["_proto.LvEvent"], None]


class TouchyError(RuntimeError):
    """Raised when the device reports a non-OK ResultCode."""

    def __init__(self, code: int, code_name: str) -> None:
        super().__init__(f"device returned {code_name} ({code})")
        self.code = code
        self.code_name = code_name


def _check(response: _proto.Response) -> _proto.Response:
    if response.code != _proto.RESULT_OK:
        name = _proto.ResultCode.Name(response.code)
        raise TouchyError(response.code, name)
    return response


class TouchyClient:
    """High-level interface to a connected Touchy-Pad device.

    Construct via :meth:`open` (uses :class:`UsbTransport`) or pass any
    custom :class:`Transport` (e.g. a loopback for tests).
    """

    def __init__(self, transport: Transport) -> None:
        self._t = transport
        self._host_handlers: dict[int, HostEventHandler] = {}
        # Serializes send_command/recv_response pairs so the high-level
        # Touchy's background event-poll thread can't interleave its
        # RPCs with foreground calls on the same transport (which would
        # cross-route the responses).
        self._rpc_lock = threading.Lock()

    @classmethod
    def open(cls) -> TouchyClient:
        return cls(UsbTransport())

    def close(self) -> None:
        self._t.close()

    def __enter__(self) -> TouchyClient:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    # -- internal RPC helper -----------------------------------------------

    def _rpc(self, command: _proto.Command) -> _proto.Response:
        which = command.WhichOneof("cmd")
        with self._rpc_lock:
            rpc_logger.debug("rpc -> %s", which)
            self._t.send_command(command.SerializeToString())
            reply = _proto.Response()
            reply.ParseFromString(self._t.recv_response())
            rpc_logger.debug("rpc <- %s code=%d", which, reply.code)
        return reply

    # -- typed wrappers ----------------------------------------------------

    def sys_board_info_get(self) -> _proto.SysBoardInfoResponse:
        reply = _check(self._rpc(_proto.Command(sys_board_info_get=_proto.SysBoardInfoGetCmd())))
        return reply.sys_board_info

    def sys_reboot_bootloader(self) -> None:
        _check(self._rpc(_proto.Command(sys_reboot_bootloader=_proto.SysRebootBootloaderCmd())))

    def screen_wake(self) -> None:
        _check(self._rpc(_proto.Command(screen_wake=_proto.ScreenWakeCmd())))

    def screen_sleep_timeout(self, timeout_ms: int) -> None:
        _check(
            self._rpc(
                _proto.Command(
                    screen_sleep_timeout=_proto.ScreenSleepTimeoutCmd(timeout_ms=timeout_ms)
                )
            )
        )

    # Maximum payload bytes per FileWriteCmd. The on-wire protobuf
    # frame must fit inside the device's RX buffer (HOST_API_RX_MAX,
    # 5 KiB in firmware/main/host_api.cpp after stage 51); we leave
    # ~1 KiB of headroom for the surrounding Command / oneof overhead.
    _FILE_WRITE_CHUNK = 4096

    def file_delete(self, path: str) -> None:
        """Delete a file or directory subtree from the device filesystem.

        *path* must be drive-prefixed, e.g. ``"F:host/screens/home.pb"``
        or ``"F:host"`` to wipe the whole host-uploaded area on flash.
        Passing ``"R:host"`` wipes the PSRAM filesystem instead.
        """
        logger.debug("file_delete: %s", path)
        _check(self._rpc(_proto.Command(file_delete=_proto.FileDeleteCmd(path=path))))

    def file_open_write(self, path: str) -> int:
        """Begin streaming a new file. Returns an opaque write handle."""
        reply = _check(
            self._rpc(_proto.Command(file_open_write=_proto.FileOpenWriteCmd(path=path)))
        )
        return reply.file_open_write.handle

    def file_write(self, handle: int, data: bytes) -> None:
        """Append a chunk of bytes to an in-progress file write."""
        _check(
            self._rpc(
                _proto.Command(file_write=_proto.FileWriteCmd(handle=handle, data=bytes(data)))
            )
        )

    def file_close(self, handle: int, commit: bool) -> None:
        """Finish (commit=True) or abort (commit=False) a streaming write."""
        _check(
            self._rpc(_proto.Command(file_close=_proto.FileCloseCmd(handle=handle, commit=commit)))
        )

    def file_save(self, path: str, data: bytes | str) -> None:
        """Write a file to the device filesystem in one logical call.

        *path* is the drive-prefixed filesystem path
        (e.g. ``"F:host/screens/home.pb"`` for persistent flash or
        ``"R:host/images/sdk_key_0.bin"`` for transient PSRAM storage).
        *data* may be ``bytes`` (for binary files such as images) or
        ``str`` (for text payloads, encoded as UTF-8).

        Image bytes (BMP / PNG / JPEG / GIF / WebP — anything Pillow can
        decode) are transparently converted to LVGL's native ``.bin``
        format before upload, so the firmware only needs its always-on
        built-in image decoder. Already-converted ``.bin`` blobs and
        non-image payloads are passed through unchanged.

        On the wire this issues a ``FileOpenWrite`` command, one or more
        ``FileWrite`` chunks (≤ 4 KiB each so the on-wire frame fits in
        the device RX buffer) and a ``FileClose(commit=True)``. If any
        chunk fails we send ``FileClose(commit=False)`` so the device
        can drop the partial file.
        """
        if isinstance(data, str):
            data = data.encode("utf-8")
        else:
            data = bytes(data)
        from .api.lvgl_image import looks_like_supported_image, rewrite_to_bin_path, to_lvgl_bin

        if looks_like_supported_image(data) and self._t.needs_image_conversion:
            original_len = len(data)
            data = to_lvgl_bin(data, dest_path=path)
            # LVGL's bin decoder selects itself by extension, so the
            # on-device file has to be named *.bin even though the
            # caller likely passed e.g. "F:host/images/avatar.png".
            path = rewrite_to_bin_path(path)
            logger.debug(
                "file_save: %s (%d bytes source → %d bytes LVGL bin)",
                path,
                original_len,
                len(data),
            )
        else:
            logger.debug("file_save: %s (%d bytes)", path, len(data))
        handle = self.file_open_write(path)
        committed = False
        try:
            for offset in range(0, len(data), self._FILE_WRITE_CHUNK):
                self.file_write(handle, data[offset : offset + self._FILE_WRITE_CHUNK])
            self.file_close(handle, commit=True)
            committed = True
        finally:
            if not committed:
                # Best-effort abort; swallow any follow-up error so the
                # original exception is what propagates.
                try:
                    self.file_close(handle, commit=False)
                except Exception:  # noqa: BLE001
                    pass

    def screen_load(self, path: str) -> None:
        """Activate a previously-uploaded screen.

        *path* is the full drive-prefixed path the screen was uploaded
        to (e.g. ``"F:host/screens/home.pb"``). Passing an empty string
        loads the device's default screen.
        """
        logger.debug("screen_load: %s", path or "(default)")
        _check(self._rpc(_proto.Command(screen_load=_proto.ScreenLoadCmd(path=path))))

    def event_consume(self) -> _proto.LvEvent | None:
        """Pop one pending event from the device queue, or return ``None``.

        Returns ``None`` on `RESULT_NOT_FOUND` (queue empty).
        """
        reply = self._rpc(_proto.Command(event_consume=_proto.EventConsumeCmd()))
        if reply.code == _proto.RESULT_NOT_FOUND:
            return None
        _check(reply)
        if reply.HasField("event_consume") and reply.event_consume.HasField("event"):
            return reply.event_consume.event
        return None

    # -- host event dispatch ------------------------------------------------

    def on_host_event(self, code: int, handler: HostEventHandler) -> None:
        """Register a callback for incoming `ActionHost` events with `host_code == code`.

        The callback receives the full :class:`_proto.LvEvent` so it can
        inspect ``user_data`` (the firing widget's id) and the ``state``
        oneof (``value`` for sliders, ``checked`` for switches/checkboxes).
        """
        self._host_handlers[code] = handler

    def _dispatch_host_event(self, evt: _proto.LvEvent) -> None:
        h = self._host_handlers.get(evt.host_code)
        if h is not None:
            h(evt)

    def stream_events(self, poll_interval_ms: int = 50) -> Iterator[_proto.LvEvent]:
        """Yield LvEvents from the device until the transport closes.

        The ESP32-S3 USB-OTG controller doesn't have a free IN endpoint
        for a dedicated event mailbox, so the host polls
        :meth:`event_consume` on the bulk command/response pair instead.
        Each call drains the device queue to empty; if the queue was empty
        we sleep ``poll_interval_ms`` before trying again. Each yielded
        event is also routed through :meth:`on_host_event` handlers (if
        any are registered for its ``host_code``).
        """
        import time

        while True:
            evt = self.event_consume()
            if evt is None:
                time.sleep(poll_interval_ms / 1000.0)
                continue
            self._dispatch_host_event(evt)
            yield evt
