"""High-level typed client for the Touchy-Pad device.

Wraps a :class:`Transport` with protobuf encoding/decoding so callers see
typed messages instead of raw bytes.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator

from . import _proto  # generated by `just build-proto-py`
from .transport import Transport, UsbTransport

HostEventHandler = Callable[["_proto.LvEvent"], None]


class TouchyError(RuntimeError):
    """Raised when the device reports a non-OK ResultCode."""

    def __init__(self, code: int, code_name: str) -> None:
        super().__init__(f"device returned {code_name} ({code})")
        self.code = code
        self.code_name = code_name


def _check(response: _proto.Response) -> _proto.Response:
    if response.code != _proto.RESULT_OK:
        name = _proto.ResultCode.Name(response.code)
        raise TouchyError(response.code, name)
    return response


class TouchyClient:
    """High-level interface to a connected Touchy-Pad device.

    Construct via :meth:`open` (uses :class:`UsbTransport`) or pass any
    custom :class:`Transport` (e.g. a loopback for tests).
    """

    def __init__(self, transport: Transport) -> None:
        self._t = transport
        self._host_handlers: dict[int, HostEventHandler] = {}

    @classmethod
    def open(cls) -> TouchyClient:
        return cls(UsbTransport())

    def close(self) -> None:
        self._t.close()

    def __enter__(self) -> TouchyClient:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    # -- internal RPC helper -----------------------------------------------

    def _rpc(self, command: _proto.Command) -> _proto.Response:
        self._t.send_command(command.SerializeToString())
        reply = _proto.Response()
        reply.ParseFromString(self._t.recv_response())
        return reply

    # -- typed wrappers ----------------------------------------------------

    def sys_version_get(self) -> _proto.SysVersionResponse:
        reply = _check(self._rpc(_proto.Command(sys_version_get=_proto.SysVersionGetCmd())))
        return reply.sys_version

    def sys_reboot_bootloader(self) -> None:
        _check(self._rpc(_proto.Command(sys_reboot_bootloader=_proto.SysRebootBootloaderCmd())))

    def screen_wake(self) -> None:
        _check(self._rpc(_proto.Command(screen_wake=_proto.ScreenWakeCmd())))

    def screen_sleep_timeout(self, timeout_ms: int) -> None:
        _check(
            self._rpc(
                _proto.Command(
                    screen_sleep_timeout=_proto.ScreenSleepTimeoutCmd(timeout_ms=timeout_ms)
                )
            )
        )

    def file_reset(self) -> None:
        """Discard all files stored on the device filesystem."""
        _check(self._rpc(_proto.Command(file_reset=_proto.FileResetCmd())))

    def file_save(self, path: str, data: bytes | str) -> None:
        """Write a file to the device filesystem.

        *path* is the virtual filesystem path (e.g. ``"screens/home.xml"`` or
        ``"img/avatar.png"``).  *data* may be ``bytes`` (for binary files such
        as images) or ``str`` (for XML layouts, encoded as UTF-8).
        """
        if isinstance(data, str):
            data = data.encode("utf-8")
        _check(self._rpc(_proto.Command(file_save=_proto.FileSaveCmd(path=path, data=data))))

    def screen_load(self, name: str) -> None:
        _check(self._rpc(_proto.Command(screen_load=_proto.ScreenLoadCmd(name=name))))

    def event_consume(self) -> _proto.LvEvent | None:
        """Pop one pending event from the device queue, or return ``None``.

        Returns ``None`` on `RESULT_NOT_FOUND` (queue empty).
        """
        reply = self._rpc(_proto.Command(event_consume=_proto.EventConsumeCmd()))
        if reply.code == _proto.RESULT_NOT_FOUND:
            return None
        _check(reply)
        if reply.HasField("event_consume") and reply.event_consume.HasField("event"):
            return reply.event_consume.event
        return None

    # -- host event dispatch ------------------------------------------------

    def on_host_event(self, code: int, handler: HostEventHandler) -> None:
        """Register a callback for incoming `ActionHost` events with `host_code == code`.

        The callback receives the full :class:`_proto.LvEvent` so it can
        inspect ``user_data`` (the firing widget's id) and the ``state``
        oneof (``value`` for sliders, ``checked`` for switches/checkboxes).
        """
        self._host_handlers[code] = handler

    def _dispatch_host_event(self, evt: _proto.LvEvent) -> None:
        h = self._host_handlers.get(evt.host_code)
        if h is not None:
            h(evt)

    def stream_events(self, poll_interval_ms: int = 50) -> Iterator[_proto.LvEvent]:
        """Yield LvEvents from the device until the transport closes.

        The ESP32-S3 USB-OTG controller doesn't have a free IN endpoint
        for a dedicated event mailbox, so the host polls
        :meth:`event_consume` on the bulk command/response pair instead.
        Each call drains the device queue to empty; if the queue was empty
        we sleep ``poll_interval_ms`` before trying again. Each yielded
        event is also routed through :meth:`on_host_event` handlers (if
        any are registered for its ``host_code``).
        """
        import time

        while True:
            evt = self.event_consume()
            if evt is None:
                time.sleep(poll_interval_ms / 1000.0)
                continue
            self._dispatch_host_event(evt)
            yield evt
