"""High-level typed client for the Touchy-Pad device.

Wraps a :class:`Transport` with protobuf encoding/decoding so callers see
typed messages instead of raw bytes.
"""

from __future__ import annotations

from collections.abc import Iterator

from . import _proto  # generated by `just build-proto-py`
from .transport import Transport, UsbTransport


class TouchyError(RuntimeError):
    """Raised when the device reports a non-OK ResultCode."""

    def __init__(self, code: int, code_name: str) -> None:
        super().__init__(f"device returned {code_name} ({code})")
        self.code = code
        self.code_name = code_name


def _check(response: _proto.Response) -> _proto.Response:
    if response.code != _proto.RESULT_OK:
        name = _proto.ResultCode.Name(response.code)
        raise TouchyError(response.code, name)
    return response


class TouchyClient:
    """High-level interface to a connected Touchy-Pad device.

    Construct via :meth:`open` (uses :class:`UsbTransport`) or pass any
    custom :class:`Transport` (e.g. a loopback for tests).
    """

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    @classmethod
    def open(cls) -> TouchyClient:
        return cls(UsbTransport())

    def close(self) -> None:
        self._t.close()

    def __enter__(self) -> TouchyClient:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()

    # -- internal RPC helper -----------------------------------------------

    def _rpc(self, command: _proto.Command) -> _proto.Response:
        self._t.send_command(command.SerializeToString())
        reply = _proto.Response()
        reply.ParseFromString(self._t.recv_response())
        return reply

    # -- typed wrappers ----------------------------------------------------

    def sys_version_get(self) -> _proto.SysVersionResponse:
        reply = _check(self._rpc(_proto.Command(sys_version_get=_proto.SysVersionGetCmd())))
        return reply.sys_version

    def sys_reboot_bootloader(self) -> None:
        _check(self._rpc(_proto.Command(sys_reboot_bootloader=_proto.SysRebootBootloaderCmd())))

    def screen_wake(self) -> None:
        _check(self._rpc(_proto.Command(screen_wake=_proto.ScreenWakeCmd())))

    def screen_sleep_timeout(self, timeout_ms: int) -> None:
        _check(self._rpc(_proto.Command(
            screen_sleep_timeout=_proto.ScreenSleepTimeoutCmd(timeout_ms=timeout_ms)
        )))

    def file_reset(self) -> None:
        """Discard all files stored on the device filesystem."""
        _check(self._rpc(_proto.Command(file_reset=_proto.FileResetCmd())))

    def file_save(self, path: str, data: bytes | str) -> None:
        """Write a file to the device filesystem.

        *path* is the virtual filesystem path (e.g. ``"screens/home.xml"`` or
        ``"img/avatar.png"``).  *data* may be ``bytes`` (for binary files such
        as images) or ``str`` (for XML layouts, encoded as UTF-8).
        """
        if isinstance(data, str):
            data = data.encode("utf-8")
        _check(self._rpc(_proto.Command(file_save=_proto.FileSaveCmd(path=path, data=data))))

    def screen_load(self, name: str) -> None:
        _check(self._rpc(_proto.Command(screen_load=_proto.ScreenLoadCmd(name=name))))


    def event_consume(self) -> _proto.Event | None:
        """Pop one pending event from the device queue, or return ``None``."""
        reply = self._rpc(_proto.Command(event_consume=_proto.EventConsumeCmd()))
        if reply.code == _proto.RESULT_NOT_FOUND:
            return None
        _check(reply)
        if reply.HasField("event_consume") and reply.event_consume.HasField("event"):
            return reply.event_consume.event
        return None

    def stream_events(self, poll_timeout_ms: int = 500) -> Iterator[_proto.Event]:
        """Yield events from the device until the transport closes.

        Reads the interrupt-IN endpoint; each packet is either a full
        :class:`_proto.Event` (yielded directly) or an ``event_ready``
        placeholder, in which case we issue an ``EventConsumeCmd`` and yield
        whatever the queue produces.
        """
        while True:
            raw = self._t.recv_event(timeout_ms=poll_timeout_ms)
            if raw is None:
                continue
            evt = _proto.Event()
            evt.ParseFromString(raw)
            if evt.WhichOneof("evt") == "event_ready":
                drained = self.event_consume()
                if drained is not None:
                    yield drained
            else:
                yield evt
